sort routers
DAMPLAB/fabrication-service pull request #2
Opened 2020-09-10 23:59 UTC by ryu-bu

Sorted the endpoints -- except for the query parameter

2020-09-11 17:33 UTC, rkrishnasanka commented on app.py
> +api.add_resource(Fabrication, '/v1/fabricationitem?order_id=<int:order_id>')
Why are there two items for `FabricationList` and `Fabrication` ?

The endpoint: `/v1/fabricationitem` should return information of a single `FabricationItem` based on whatever item ID is associated with it. Its possible that I understood the functionality incorreclty.

2020-09-11 17:37 UTC, rkrishnasanka commented on controllers/fabricationlifecycle.py
>  class FabricationControl:
I guess I missed this last time but, the name of the python file and the class should be the name (case not included)

2020-09-11 17:40 UTC, rkrishnasanka commented on resources/user.py
> +
User endpoint `POST` request has different functionality. All updates to FabricationItem and SubmissionItem need to be done through their corresponding endpoints.

2020-09-11 17:42 UTC, rkrishnasanka commented on resources/user.py
> +        return FabricationControl.usr_comp(item['order_id'], item['stage'])
Similarly, the User endpoint POST and PUT requests should only modify the User object and not anything else

2020-09-11 17:44 UTC, rkrishnasanka requested changes
Address the changes I pointed out here. Basically you need to follow what the story required in terms of setting up the endpoints

2020-09-11 18:11 UTC, ryu-bu commented on app.py
> +api.add_resource(Fabrication, '/v1/fabricationitem?order_id=<int:order_id>')
one returns all the fabrication items and the other only returns the item specified

2020-09-11 18:15 UTC, ryu-bu commented on resources/user.py
> +
this is just a place holder for today's demo – they are there simply because I copied the entire code from fabricationitem.py. I was planning to organize this after the machinist and manager list is finalized. All the post requests from the UI are either to the submissionitem or fabrication but never to user for now.

2020-09-11 18:16 UTC, ryu-bu commented on app.py
> +api.add_resource(Fabrication, '/v1/fabricationitem?order_id=<int:order_id>')
so far the query parameter is not working... it just returns all the fabrication items

2020-09-23 15:50 UTC, rkrishnasanka approved these changes
We will do another code review later once the whole pipeline is implemented.

2020-09-23 15:53 UTC, merged

2020-09-23 15:54 UTC, rkrishnasanka commented
This needs a deeper code review @0x174 , I could use your help here to make sure that the Auth system, etc. is similar to what you will be using for your tools too. It'd be better if there was 1 auth system implementation across the different DAMP tools. (Not necessarily the same database) but rather in terms of libraries, that would help ensure the security/maintainability of all the DAMP services.